---
apigee_admin_password: Apigee11

apigee_tls_mp_keystore_type: jks
apigee_tls_mp_keystore_dest: /opt/apigee/customer/keystore-mp.jks
apigee_tls_mp_keystore_validity: 7300

# Set these for an existing keystore
apigee_tls_mp_keystore_src:
apigee_tls_mp_keystore_keyalias: apigee-mp
apigee_tls_mp_keystore_password: '{{ apigee_admin_password }}'

apigee_tls_mp_port: 8998
apigee_tls_mp_properties_path: /opt/apigee/customer/application/message-processor.properties
