---
- name: Set setup.sh path
  set_fact:
    setup: /opt/apigee/apigee-setup/bin/setup.sh

- import_tasks: setup-pdb.yml
  when: ('pdb' in apigee.profiles)

- import_tasks: installation-path.yml
  when: ('dp' in apigee.profiles)

- name: Install sendmail
  package:
    name: sendmail
    state: present
  when: ('dp' in apigee.profiles)

- name: Setup developer portal servers
  shell: '{{ setup }} -f {{ dp_response }} -p dp'
  when: ('dp' in apigee.profiles)

# Developer Portal autostart script doesn't work
- name: Check for Developer Portal
  stat:
    path: /opt/apigee/apigee-drupal-devportal
  register: apigee_drupal_path

- name: Enable automatic start
  command: /opt/apigee/apigee-service/bin/apigee-all enable_autostart
  when: apigee_enable_autostart
  ignore_errors: '{{ apigee_drupal_path.stat.exists }}'
