---
- name: Set Apigee facts
  apigee_facts:
    hostvars: '{{ hostvars }}'
    topology: '{{ apigee_topology }}'
    my_hostname: '{{ apigee_cluster_hostname }}'

- name: Show Apigee facts
  debug:
    var: apigee
  when: apigee_debug
